// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Context;

namespace Store.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20181105112648_StoreDB")]
    partial class StoreDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Store.Models.StoreInfo", b =>
                {
                    b.Property<decimal>("StoreCash");

                    b.Property<string>("StoreLog");

                    b.HasKey("StoreCash");

                    b.ToTable("StoreInfo");
                });

            modelBuilder.Entity("Store.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<int>("InStock");

                    b.Property<int>("MaxStock");

                    b.Property<decimal>("Overcharge");

                    b.Property<decimal>("Price");

                    b.Property<int>("Type");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
